# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'riot_ai_mainwindow_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt
# from PyQt5.QtWidgets import QMenuBar


class Ui_MainWindow(object):
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1356, 695)
        # Setting contextMenuPolicy
        self.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        # MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks | QtWidgets.QMainWindow.AnimatedDocks)
        # MainWindow.setStyleSheet("#toolBar_Devices QToolButton {\n"
        #                          "width: 50px;\n"
        #                          "height: 55px;\n"
        #                          "border:solid 1px black opacity 0.4;\n"
        #                          "background-none;\n"
        #                          "}\n"
        #                          "\n"
        #                          "#toolBar_General QToolButton {\n"
        #                          "width: 36px;\n"
        #                          "height: 36px;\n"
        #                          "border:solid 1px black opacity 0.4;\n"
        #                          "background-none;\n"
        #                          "}\n"
        #                          "\n"
        #                          "")
        self.uiCentralWidget = QtWidgets.QWidget(self)
        # self.uiCentralWidget = QtWidgets.QLabel("Hello, World")
        # self.uiCentralWidget.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.uiCentralWidget.setObjectName("uiCentralWidget")
        self.setCentralWidget(self.uiCentralWidget)

        self.setWindowModality(QtCore.Qt.NonModal)



        ####### adding a menu bar
        menuBar = QtWidgets.QMenuBar(self)
        self.setMenuBar(menuBar)
        # Creating menus using a title
        fileMenu = menuBar.addMenu("&File")
        editMenu = menuBar.addMenu("&Edit")
        helpMenu = menuBar.addMenu("&Help")

        ##### buttons for the uiToolBar ######
        self.uiHomePageAction = QtWidgets.QAction(self.uiCentralWidget)
        icon12 = QtGui.QIcon(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png')
        icon12.addPixmap(QtGui.QPixmap(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png'),
                         QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png'),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiHomePageAction.setIcon(icon12)
        self.uiHomePageAction.setObjectName("logo")

        ######## secound button
        self.uiHome2PageAction = QtWidgets.QAction(self.uiCentralWidget)
        icon122 = QtGui.QIcon(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png')
        icon122.addPixmap(QtGui.QPixmap(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png'),
                         QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon122.addPixmap(QtGui.QPixmap(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png'),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiHome2PageAction.setIcon(icon122)
        self.uiHome2PageAction.setObjectName("logo")

        ######## third button
        self.uiHome3PageAction = QtWidgets.QAction(self.uiCentralWidget)
        icon123 = QtGui.QIcon(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png')
        icon123.addPixmap(
            QtGui.QPixmap(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png'),
            QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon123.addPixmap(
            QtGui.QPixmap(r'C:\Users\Yael\Desktop\elbit\skynet_hackaton\new-skynet\img\riot_ai_scull.png'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiHome3PageAction.setIcon(icon123)
        self.uiHome3PageAction.setObjectName("logo")

        # self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        # self.pushButton.setGeometry(QtCore.QRect(60, 80, 201, 31))
        # self.pushButton.setObjectName("pushButton")

        self.uiToolBar = QtWidgets.QToolBar(self.uiCentralWidget)
        self.uiToolBar.setIconSize(QtCore.QSize(70, 40))
        self.uiToolBar.setObjectName("menuToolBar")
        self.addToolBar(QtCore.Qt.TopToolBarArea, self.uiToolBar)
        #add button functionality
        self.uiToolBar.addAction(self.uiHomePageAction)
        self.uiToolBar.addAction(self.uiHome2PageAction)
        self.uiToolBar.addAction(self.uiHome3PageAction)
        self.uiToolBar.addSeparator()

        ######### events scroll area
        self.eventsScrollArea = QtWidgets.QScrollArea(self.uiCentralWidget)
        self.eventsScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.eventsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # (width,height_top ,width, height_bottom)
        self.eventsScrollArea.setGeometry(QtCore.QRect(1205, -2, 150, 625))
        self.eventsScrollArea.setWidgetResizable(True)
        self.eventsScrollArea.setObjectName("eventsScrollArea")
        self.eventsScrollAreaWidgetContents = QtWidgets.QWidget()
        self.eventsScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 549))
        self.eventsScrollAreaWidgetContents.setObjectName("eventsScrollAreaWidgetContents")
        self.eventsScrollArea.setFocusPolicy(QtCore.Qt.NoFocus)

        self.eventsLayoutArea = QtWidgets.QVBoxLayout(self.eventsScrollAreaWidgetContents)
        self.eventsLayoutArea.addItem(
            QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding))
        self.eventsScrollArea.setWidget(self.eventsScrollAreaWidgetContents)

        ########### event data scroll area
        self.eventDataScrollArea = QtWidgets.QScrollArea(self.uiCentralWidget)
        # self.eventDataScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.eventDataScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # (width,height_top ,width, height_bottom)
        self.eventDataScrollArea.setGeometry(QtCore.QRect(780, -2, 426, 625))
        self.eventDataScrollArea.setWidgetResizable(True)
        self.eventDataScrollArea.setObjectName("eventDataScrollArea")
        self.eventDataScrollAreaWidgetContent = QtWidgets.QWidget()
        self.eventDataScrollAreaWidgetContent.setGeometry(QtCore.QRect(0, 0, 309, 549))
        self.eventDataScrollAreaWidgetContent.setObjectName("eventDataScrollAreaWidgetContent")
        self.eventDataScrollArea.setFocusPolicy(QtCore.Qt.NoFocus)

        self.eventDataLayoutArea = QtWidgets.QVBoxLayout(self.eventDataScrollAreaWidgetContent)
        self.eventDataLayoutArea.addItem(
            QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding))
        self.eventDataScrollArea.setWidget(self.eventDataScrollAreaWidgetContent)

        count = self.eventDataLayoutArea.count() - 1
        groupbox_eventData = QtWidgets.QGroupBox("Event Data:", self.eventDataScrollArea)
        self.eventDataLayoutArea.insertWidget(count, groupbox_eventData)
        gridLayout = QtWidgets.QGridLayout(groupbox_eventData)
        self.event_data = QtWidgets.QLabel("", groupbox_eventData)
        gridLayout.addWidget(self.event_data, 0, 0, 1, 1)
        self.event_data.hide()



        ##### making the video player
        # self.video_output = self.makeVideoWidget()

        self.videoLayoutArea = QtWidgets.QVBoxLayout(self.uiCentralWidget)
        # self.widget_video.setLayout(self.videoLayoutArea)
        # self.videoLayoutArea.setGeometry(QtCore.QRect(10, 160, 471, 241))

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Riot-AI"))

        # self.eventToolBar.setText(_translate("eventToolBar", "eventToolBar"))
        # self.uiToolBar.setText(_translate("uiToolBar", "menuToolBar"))
        self.uiHomePageAction.setText(_translate("logo", "Riot-AI"))
        self.uiHome2PageAction.setText(_translate("logo", "Riot-AI"))
        self.uiHome3PageAction.setText(_translate("logo", "Riot-AI"))
        # self.logo.setText(_translate("MainWindow", "Riot-AI"))

from PyQt5.QtMultimediaWidgets import QVideoWidget
from event_summary_view import EventSummaryView

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
