# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'riot_ai_mainwindow_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# from PyQt5.QtWidgets import QMenuBar

AI_FIRE_PNG = r'img/riot_ai_fire.png'
RIOT_AI_SCULL_PNG = r'img/riot_ai_scull.png'


class Ui_MainWindow(object):
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1356, 695)
        # Setting contextMenuPolicy
        self.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)

        self.uiCentralWidget = QtWidgets.QWidget()
        # self.uiCentralWidget = QtWidgets.QLabel("Hello, World")
        # self.uiCentralWidget.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.uiCentralWidget.setObjectName("uiCentralWidget")
        self.setCentralWidget(self.uiCentralWidget)
        self.setWindowModality(QtCore.Qt.NonModal)

        ####### adding a menu bar
        menuBar = QtWidgets.QMenuBar()
        self.setMenuBar(menuBar)
        # Creating menus using a title
        fileMenu = menuBar.addMenu("&File")
        editMenu = menuBar.addMenu("&Edit")
        helpMenu = menuBar.addMenu("&Help")

        ##### buttons for the uiToolBar ######
        self.uiHomePageAction = QtWidgets.QAction(self.uiCentralWidget)
        icon12 = QtGui.QIcon(RIOT_AI_SCULL_PNG)
        icon12.addPixmap(QtGui.QPixmap(RIOT_AI_SCULL_PNG),
                         QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(RIOT_AI_SCULL_PNG),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiHomePageAction.setIcon(icon12)
        self.uiHomePageAction.setObjectName("logo")

        # ######## secound button
        # self.uiHome2PageAction = QtWidgets.QAction(self.uiCentralWidget)
        # icon122 = QtGui.QIcon(RIOT_AI_SCULL_PNG)
        # icon122.addPixmap(
        #     QtGui.QPixmap(RIOT_AI_SCULL_PNG),
        #     QtGui.QIcon.Active, QtGui.QIcon.Off)
        # icon122.addPixmap(
        #     QtGui.QPixmap(RIOT_AI_SCULL_PNG),
        #     QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.uiHome2PageAction.setIcon(icon122)
        # self.uiHome2PageAction.setObjectName("logo")

        # ######## third button
        # self.uiHome3PageAction = QtWidgets.QAction(self.uiCentralWidget)
        # icon123 = QtGui.QIcon(RIOT_AI_SCULL_PNG)
        # icon123.addPixmap(
        #     QtGui.QPixmap(RIOT_AI_SCULL_PNG),
        #     QtGui.QIcon.Active, QtGui.QIcon.Off)
        # icon123.addPixmap(
        #     QtGui.QPixmap(RIOT_AI_SCULL_PNG),
        #     QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.uiHome3PageAction.setIcon(icon123)
        # self.uiHome3PageAction.setObjectName("logo")

        self.uiToolBar = QtWidgets.QToolBar(self.uiCentralWidget)
        self.uiToolBar.setIconSize(QtCore.QSize(70, 40))
        self.uiToolBar.setObjectName("menuToolBar")
        self.addToolBar(QtCore.Qt.TopToolBarArea, self.uiToolBar)
        # add button functionality
        self.uiToolBar.addAction(self.uiHomePageAction)
        # self.uiToolBar.addAction(self.uiHome2PageAction)
        # self.uiToolBar.addAction(self.uiHome3PageAction)
        self.uiToolBar.addSeparator()

        ######### events scroll area
        self.eventsScrollArea = QtWidgets.QScrollArea(self.uiCentralWidget)
        self.eventsScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.eventsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # setGeometry(left, top, width, height)
        self.eventsScrollArea.setGeometry(QtCore.QRect(1205, -2, 150, 625))
        self.eventsScrollArea.setWidgetResizable(True)
        self.eventsScrollArea.setObjectName("eventsScrollArea")
        self.eventsScrollAreaWidgetContents = QtWidgets.QWidget()
        self.eventsScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 549))
        self.eventsScrollAreaWidgetContents.setObjectName("eventsScrollAreaWidgetContents")
        self.eventsScrollArea.setFocusPolicy(QtCore.Qt.NoFocus)

        self.eventsLayoutArea = QtWidgets.QVBoxLayout(self.eventsScrollAreaWidgetContents)
        self.eventsLayoutArea.addWidget(QtWidgets.QLabel("Events:"))
        self.eventsLayoutArea.addItem(
            QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding))
        self.eventsScrollArea.setWidget(self.eventsScrollAreaWidgetContents)

        ########### event data scroll area
        self.eventDataScrollArea = QtWidgets.QScrollArea(self.uiCentralWidget)
        # self.eventDataScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.eventDataScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # setGeometry(left, top, width, height)
        self.eventDataScrollArea.setGeometry(QtCore.QRect(780, -2, 426, 625))
        self.eventDataScrollArea.setWidgetResizable(True)
        self.eventDataScrollArea.setObjectName("eventDataScrollArea")
        self.eventDataScrollAreaWidgetContent = QtWidgets.QWidget()
        self.eventDataScrollAreaWidgetContent.setGeometry(QtCore.QRect(0, 0, 309, 549))
        self.eventDataScrollAreaWidgetContent.setObjectName("eventDataScrollAreaWidgetContent")
        self.eventDataScrollArea.setFocusPolicy(QtCore.Qt.NoFocus)

        self.eventDataLayoutArea = QtWidgets.QVBoxLayout(self.eventDataScrollAreaWidgetContent)
        self.eventDataLayoutArea.addItem(
            QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding))
        self.eventDataScrollArea.setWidget(self.eventDataScrollAreaWidgetContent)

        count = self.eventDataLayoutArea.count() - 1
        groupbox_eventData = QtWidgets.QGroupBox("Event Data:", self.eventDataScrollArea)
        self.eventDataLayoutArea.insertWidget(count, groupbox_eventData)
        gridLayout = QtWidgets.QGridLayout(groupbox_eventData)
        self.event_data = QtWidgets.QLabel("", groupbox_eventData)
        # image = QtGui.QImage(picture, picture.shape[1], picture.shape[0], QtGui.QImage.Format_RGB888)
        event_pixmap = QtGui.QPixmap(RIOT_AI_SCULL_PNG)
        self.event_img_label = QtWidgets.QLabel()
        self.event_img_label.setPixmap(event_pixmap.scaled(self.eventDataScrollAreaWidgetContent.width() - 50,
                                                           self.eventDataScrollAreaWidgetContent.height() - 50,
                                                           QtCore.Qt.KeepAspectRatio))
        self.event_img_label.adjustSize()
        gridLayout.addWidget(self.event_data, 0, 0)
        gridLayout.addWidget(self.event_img_label, 1, 0)
        # self.event_data.hide()

        ##### making the video player
        ########### event data scroll area
        self.ScrollArea = QtWidgets.QScrollArea(self.uiCentralWidget)
        self.ScrollArea.setGeometry(QtCore.QRect(0, -2, 780, 625))
        self.LayoutArea = QtWidgets.QVBoxLayout(self.ScrollArea)
        self.LayoutArea.setGeometry(QtCore.QRect(0, -2, 780, 625))
        self.video_label = QtWidgets.QLabel()
        video_pixmap = QtGui.QPixmap(AI_FIRE_PNG)
        self.video_label.setPixmap(video_pixmap)
        self.LayoutArea.insertWidget(1, self.video_label)
        self.video_label.setSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Riot-AI"))

        # self.eventToolBar.setText(_translate("eventToolBar", "eventToolBar"))
        # self.uiToolBar.setText(_translate("uiToolBar", "menuToolBar"))
        self.uiHomePageAction.setText(_translate("logo", "Riot-AI"))
        # self.uiHome2PageAction.setText(_translate("logo", "Riot-AI"))
        # self.uiHome3PageAction.setText(_translate("logo", "Riot-AI"))
        # self.logo.setText(_translate("MainWindow", "Riot-AI"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
